version: '3.8'
services:
  lumina_rag:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: lumina_rag
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=./src
    command: python3 .py
networks:
  app_name:
    name: ${NETWORK_NAME}
    external: true
