FROM python:3.12-slim

WORKDIR /app

# Instala dependencias del sistema si necesitas (ejemplo: para docx/pdf)
RUN apt-get update && apt-get install -y \
    build-essential \
    libmagic-dev \
    && rm -rf /var/lib/apt/lists/*

# Copia los archivos del proyecto
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=./src

CMD ["python3", "example.py"]