services:
  lumina_rag:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumina_rag
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=./src
    # Comando por defecto del Dockerfile (desarrollo con --reload)
    # Para producción, cambia el comando en el Dockerfile descomentando la sección de PROD
networks:
  app_name:
    name: ${NETWORK_NAME}
    external: true